CREATE TABLE basic_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    question_text TEXT NOT NULL,
    answer_text TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE basic_question_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL REFERENCES basic_questions(id) ON DELETE CASCADE,
    attempted_by_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    submitted_answer TEXT NOT NULL,
    correct BOOLEAN NOT NULL,
    attempted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_basic_questions_created_by_user_id ON basic_questions(created_by_user_id);
CREATE INDEX idx_basic_question_attempts_question_id ON basic_question_attempts(question_id);
CREATE INDEX idx_basic_question_attempts_attempted_by_user_id ON basic_question_attempts(attempted_by_user_id);
