-- Early prototype reset:
-- Qwizle previously used basic_questions/basic_question_attempts while the
-- product shape was still disposable. The unified question model replaces
-- that prototype schema with one canonical question lifecycle.

CREATE TABLE questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    type VARCHAR(40) NOT NULL,
    prompt_text TEXT NOT NULL,
    prompt_media_json TEXT NOT NULL DEFAULT '[]',
    definition_json TEXT NOT NULL,
    explanation TEXT,
    difficulty VARCHAR(40),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_questions_supported_type CHECK (type IN ('SINGLE_ANSWER', 'MULTIPLE_ANSWER', 'MULTIPLE_CHOICE', 'MATCH'))
);

CREATE TABLE question_tags (
    question_id BIGINT NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
    tag VARCHAR(80) NOT NULL,
    PRIMARY KEY (question_id, tag)
);

CREATE TABLE question_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
    attempted_by_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    submission_json TEXT NOT NULL,
    result_json TEXT NOT NULL,
    score NUMERIC(8, 3) NOT NULL,
    max_score NUMERIC(8, 3) NOT NULL,
    correct BOOLEAN NOT NULL,
    attempted_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_question_attempts_score_range CHECK (score >= 0 AND max_score > 0 AND score <= max_score)
);

CREATE INDEX idx_questions_created_by_user_id ON questions(created_by_user_id);
CREATE INDEX idx_question_attempts_question_id ON question_attempts(question_id);
CREATE INDEX idx_question_attempts_attempted_by_user_id ON question_attempts(attempted_by_user_id);
