CREATE TABLE quizzes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title VARCHAR(160) NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE quiz_questions (
    quiz_id BIGINT NOT NULL REFERENCES quizzes(id) ON DELETE CASCADE,
    question_id BIGINT NOT NULL REFERENCES basic_questions(id) ON DELETE CASCADE,
    position INTEGER NOT NULL,
    PRIMARY KEY (quiz_id, question_id),
    CONSTRAINT uq_quiz_questions_position UNIQUE (quiz_id, position),
    CONSTRAINT chk_quiz_questions_position_positive CHECK (position > 0)
);

CREATE INDEX idx_quizzes_created_by_user_id ON quizzes(created_by_user_id);
CREATE INDEX idx_quiz_questions_question_id ON quiz_questions(question_id);
